name: python 3.8
dependencies:
  - python=3.8
  - numpy
  - plotly
  - jupyter_dash
  - dash_core_components
  - dash_html_components
  - dash.dependencies
  - matplotlib.pyplot
  - pandas
  - sidetable
  - sqlite3 
